In [43]:
# import the necessary libraries 
import numpy as np
import pandas as pd

In [44]:
data = pd.read_csv('breast_cancer.csv')
print(data.shape)
data.head()


(569, 33)


id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [45]:
# slice the data suitably 
data = data.iloc[: , 0:32]
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [46]:
# assign data-fields to X(Feature matrix) and Y(Target matrix)
X = data.iloc[: ,2:].values
Y = data['diagnosis'].values

In [47]:
X[:5]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e

In [48]:
Y[:5]

array(['M', 'M', 'M', 'M', 'M'], dtype=object)

In [49]:
# split the data 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X, Y , test_size = 0.2,random_state = 500)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 30)
(114, 30)
(455,)
(114,)


In [50]:
(y_train == "M").sum()

177

In [51]:
(y_train == "B").sum()

278

In [52]:
len(y_train)

455

In [53]:
# create a baseline model for prediction
print (278/len(y_train))
baseline_pred = ["B"] * len(y_train)

0.610989010989011


In [54]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_train,baseline_pred)

0.610989010989011

In [55]:
confusion_matrix(y_train,baseline_pred)

array([[278,   0],
       [177,   0]], dtype=int64)

In [58]:
print (classification_report(y_train,baseline_pred))
                            

              precision    recall  f1-score   support

           B       0.61      1.00      0.76       278
           M       0.00      0.00      0.00       177

    accuracy                           0.61       455
   macro avg       0.31      0.50      0.38       455
weighted avg       0.37      0.61      0.46       455



C:\Users\Nik\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [59]:
# Naive bayes algorithm
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(x_train,y_train)


GaussianNB(priors=None, var_smoothing=1e-09)

In [60]:
accuracy_score(y_train,nb_model.predict(x_train)) # training

0.9318681318681319

In [61]:
accuracy_score(y_test,nb_model.predict(x_test))  # testing

0.9736842105263158

In [62]:
print("Confusion matrix for training is :\n", confusion_matrix(y_train,nb_model.predict(x_train)))

Confusion matrix for training is :
 [[269   9]
 [ 22 155]]


In [63]:
print("Confusion matrix for testing is :\n", confusion_matrix(y_test,nb_model.predict(x_test)))

Confusion matrix for testing is :
 [[78  1]
 [ 2 33]]


In [64]:
print("Classification report for testing is :\n", classification_report(y_test,nb_model.predict(x_test)))

Classification report for testing is :
               precision    recall  f1-score   support

           B       0.97      0.99      0.98        79
           M       0.97      0.94      0.96        35

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [65]:
print("Classification report for training is : \n", classification_report(y_train,nb_model.predict(x_train)))

Classification report for training is : 
               precision    recall  f1-score   support

           B       0.92      0.97      0.95       278
           M       0.95      0.88      0.91       177

    accuracy                           0.93       455
   macro avg       0.93      0.92      0.93       455
weighted avg       0.93      0.93      0.93       455



In [66]:
# predicting train and test wrt to probabilities greater than 0.25 as Malignant
pred_train = nb_model.predict_proba(x_train)[:,1] > 0.25
pred_test = nb_model.predict_proba(x_test)[: ,1] > 0.25

print("Confusion matrix for prediction training data is :\n",confusion_matrix(y_train == 'M',pred_train))
print("Confusion matrix for prediction testing data is :\n",confusion_matrix(y_test == 'M',pred_test))

Confusion matrix for prediction training data is :
 [[268  10]
 [ 19 158]]
Confusion matrix for prediction testing data is :
 [[78  1]
 [ 2 33]]
